### ISSUE TITLE
Classroom - Next/previous question button issues

### ISSUE THREAD

**Issue by maxsv0** [maxsv0/mega-iq-ui#137]
* bug allows to click next on the last question and move to "question 0"
* next/prev button should cycle between questions that are not answered yet

**Comment by Aisangon** [comment]
> next/prev button should cycle between questions that are not answered yet
@maxsv0 
Question about this: what happens when the user wants to to go back to a question already submitted, but the buttons only cycle through question that are not answered yet? how should he do that?
What should happens to the test when all questions are answered? should the user then be able to click through all questions or not be able to navigate through any questions anymore?

**Comment by maxsv0** [comment]
to @Aisangon 

> Question about this: what happens when the user wants to to go back to a question already submitted, but the buttons only cycle through question that are not answered yet? how should he do that?

He could use direct navigation, so click question number.



> What should happens to the test when all questions are answered? 

I think It's a good idea to disable both buttons and right here say something like "the test is finished please press the submit button to submit your result"

**Comment by Aisangon** [comment]
@maxsv0  ok, i understand, I would suggest removing the previous button on the first question and the next button on the last question for better ux, instead of disabling, what do you think?

**Comment by maxsv0** [comment]
@Aisangon 
>  I would suggest removing the previous button on the first question and the next button on the last question for better ux, instead of disabling, what do you think?

OK!
Just make sure that UI doesn't break when the button is removed.
