### ISSUE TITLE
Customize background image for private profile in settings menu

### ISSUE THREAD

**Issue by Aisangon** [maxsv0/mega-iq-ui#55]
-Include Color picker/ linear gradient generator to add backgrounds to private profile

**Comment by maxsv0** [comment]
> picked bg class as string
is a good option. but having class as a string means that you want to predefine some backgrounds and let to chose between them.

In case if you want to have color picker for gradient, to let the user chose any colors, storing a class name is not enough, we need to store all generated CSS of gradient.

Both options are easy to implement and we better use back-end API rather than 3d party.

**Comment by Aisangon** [comment]
first option is what i was thinking, i can predefine 10 bg gradients ie. bg-user1, bg-user1 etc. and create a grid similar to predefined user avatar with 10 backgrounds to choose from and api can accept the picked bg class a string and be part of currentUser response object, right?

**Comment by maxsv0** [comment]
to @Aisangon 100% yes :)

**Comment by Aisangon** [comment]
let me know when you have updated the api
